// LLG Medicine - pharmacy labels for TerjeMedicine items.
//
// This mod re-opens NO config classes. Every earlier attempt did, and every
// failure traced back to that: when a re-opened class names a parent that
// differs from what the shipped mod uses, the engine replaces the class
// instead of merging into it, and the item loses its model and health.
//
// Instead the label text lives here, keyed by item class name, and is handed
// to the inventory tooltip through DescriptionOverride - the same hook
// TerjeCore uses to build its own effects block. Nothing about the items
// themselves changes.

class LLGMedicineLabels
{
	static ref map<string, string> s_Labels;

	static string Get(string type)
	{
		if (!s_Labels)
		{
			s_Labels = new map<string, string>();
			Fill();
		}
		string label;
		if (s_Labels.Find(type, label))
		{
			return label;
		}
		return "";
	}

	static void Fill()
	{
		s_Labels.Insert("TerjePillsAnalgin", "ANALGIN (METAMIZOLE) 500 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR MILD TO MODERATE PAIN.<br/>PAIN L1 for 8 min 20 sec<br/>OVERDOSE 0.15 (Low Risk). Short acting. Wears off quickly under stress.<br/>LOT 1329D - EXP 2029-06-13");
		s_Labels.Insert("TerjePillsNimesulid", "NIMESULIDE 100 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR PAIN.<br/>PAIN L1 for 10 min<br/>OVERDOSE 0.25 (Moderate Risk). Take with food. May irritate the stomach.<br/>LOT 1458Y - EXP 2031-12-12");
		s_Labels.Insert("TerjePillsParacetamol", "PARACETAMOL 500 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR PAIN AND EARLY COLD/PNEUMONIA.<br/>PAIN L1 for 3 min 20 sec - COLD/PNEUMONIA L1 for 2 min<br/>OVERDOSE 0.45 (Moderate Risk). Liver damage occurs above the labelled dose.<br/>LOT 8820N - EXP 2031-08-24");
		s_Labels.Insert("TerjePillsIbuprofen", "IBUPROFEN 400 MG - ORAL CAPSULE<br/>TAKE 1 CAPSULE BY MOUTH FOR PAIN AND COLD/PNEUMONIA.<br/>PAIN L1 for 10 min - COLD/PNEUMONIA L2 for 5 min<br/>OVERDOSE 0.35 (Moderate Risk). Take with food. May irritate the stomach.<br/>LOT 3699P - EXP 2030-04-06");
		s_Labels.Insert("TerjePillsNurofen", "NUROFEN (IBUPROFEN LYSINE) 512 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR COLD/PNEUMONIA.<br/>PAIN L1 for 5 min 50 sec - COLD/PNEUMONIA L2 for 5 min<br/>OVERDOSE 0.52 (High Risk). Fast acting. One tablet per dose, no stacking.<br/>LOT 8743W - EXP 2030-04-28");
		s_Labels.Insert("TerjePillsAmoxiclav", "AMOXICLAV 875 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR COLD/PNEUMONIA.<br/>COLD/PNEUMONIA L2 for 20 min<br/>OVERDOSE 0.75 (High Risk). Full-strength antibiotic. Space doses well apart.<br/>LOT 5429G - EXP 2029-09-22");
		s_Labels.Insert("TerjePillsPiperacylin", "PIPERACILLIN 500 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR COLD/PNEUMONIA.<br/>COLD/PNEUMONIA L2 for 18 min 20 sec<br/>OVERDOSE 0.45 (Moderate Risk). Finish the course. Never double a missed dose.<br/>LOT 7511J - EXP 2030-10-12");
		s_Labels.Insert("TerjePillsAmibaktam", "AMIBACTAM 250 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH AT THE FIRST SIGN OF COLD/PNEUMONIA.<br/>COLD/PNEUMONIA L1 for 1 min<br/>OVERDOSE 0.05 (Low Risk). Weak and very short acting. Not for pneumonia.<br/>LOT 6376J - EXP 2029-09-09");
		s_Labels.Insert("TerjePillsPolisorb", "POLYSORB (SILICON DIOXIDE) 3 G - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR MILD FOOD POISONING.<br/>FOOD POISONING L1 for 5 min<br/>OVERDOSE 0.05 (Low Risk). Drink plenty of water with each dose.<br/>LOT 1043E - EXP 2031-12-02");
		s_Labels.Insert("TerjePillsFtalazol", "PHTHALAZOLE 500 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR PERSISTENT FOOD POISONING.<br/>FOOD POISONING L1 for 20 min<br/>OVERDOSE 0.25 (Moderate Risk). Long acting. Wait before taking another.<br/>LOT 6977Z - EXP 2029-11-20");
		s_Labels.Insert("TerjePillsMesalazin", "MESALAZINE 800 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR SEVERE FOOD POISONING.<br/>FOOD POISONING L2 for 10 min<br/>OVERDOSE 0.35 (Moderate Risk). Do not combine with other gut medication.<br/>LOT 2618G - EXP 2031-05-17");
		s_Labels.Insert("TerjePillsNoopept", "NOOPEPT 10 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR PAIN AND CONCUSSION.<br/>PAIN L1 for 6 min 20 sec - CONCUSSION for 6 min 20 sec<br/>OVERDOSE 0.35 (Moderate Risk). May cause irritability and disturbed sleep.<br/>LOT 4463B - EXP 2029-07-06");
		s_Labels.Insert("TerjePillsVikasol", "VIKASOL (VITAMIN K3) 15 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH TO SLOW THE BLEEDING RATE.<br/>BLEEDING RATE L1 for 5 min<br/>OVERDOSE 0.15 (Low Risk). Does not replace a bandage or tourniquet.<br/>LOT 8235Y - EXP 2029-01-02");
		s_Labels.Insert("TerjePillsIrovit", "IROVIT (FERROUS SULFATE) 325 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR BLOOD REGENERATION.<br/>BLOOD REGEN L1 for 2 min<br/>OVERDOSE 0.3 (Moderate Risk). May cause nausea. Take with food.<br/>LOT 5389E - EXP 2028-03-11");
		s_Labels.Insert("TerjePillsMagnesiumSulfate", "MAGNESIUM SULFATE 500 MG - ORAL CAPSULE<br/>TAKE 1 CAPSULE BY MOUTH FOR BLOOD REGENERATION.<br/>BLOOD REGEN L2.5 for 2 min<br/>OVERDOSE 0.3 (Moderate Risk). May cause flushing and light-headedness.<br/>LOT 7573A - EXP 2028-12-02");
		s_Labels.Insert("TerjePillsAdepress", "ADEPRESS (PAROXETINE) 20 MG - ORAL CAPSULE - RX ONLY<br/>TAKE 1 CAPSULE BY MOUTH FOR MENTAL HEALTH.<br/>MENTAL HEALTH L1 for 2 min 30 sec<br/>OVERDOSE 0.2 (Moderate Risk). May cause drowsiness. Do not take with alcohol.<br/>LOT 6095W - EXP 2028-09-21");
		s_Labels.Insert("TerjePillsAgteminol", "AGTEMINOL 25 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR MENTAL HEALTH.<br/>MENTAL HEALTH L1 for 2 min<br/>OVERDOSE 0.2 (Moderate Risk). May cause mild drowsiness.<br/>LOT 5234J - EXP 2029-01-25");
		s_Labels.Insert("TerjePillsVenlafaxine", "VENLAFAXINE 75 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR MENTAL HEALTH.<br/>MENTAL HEALTH L1 for 4 min 10 sec<br/>OVERDOSE 0.3 (Moderate Risk). Do not stop suddenly after repeated use.<br/>LOT 1944D - EXP 2030-12-01");
		s_Labels.Insert("TerjePillsRombiopental", "ROMBIOPENTAL 100 MG - ORAL CAPSULE - RX ONLY<br/>TAKE 1 CAPSULE BY MOUTH BEFORE CHEMICAL EXPOSURE.<br/>CHEMICAL POISONING L1 for 30 sec<br/>OVERDOSE 0.15 (Low Risk). Protective window is under one minute.<br/>LOT 6782T - EXP 2031-08-23");
		s_Labels.Insert("TerjePillsB190", "TABLETS B190 150 MG - ORAL CAPSULE - RX ONLY<br/>TAKE 1 CAPSULE BY MOUTH BEFORE ENTERING A RADIATION ZONE.<br/>RADIATION L1 for 2 min 20 sec<br/>OVERDOSE 0.3 (Moderate Risk). Preventive only. Does nothing once exposed.<br/>LOT 8945R - EXP 2030-11-18");
		s_Labels.Insert("TerjePillsPotassiumIodide", "POTASSIUM IODIDE 130 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH BEFORE ENTERING A RADIATION ZONE.<br/>RADIATION L1 for 1 min<br/>OVERDOSE 0.2 (Moderate Risk). Protects the thyroid only. Short duration.<br/>LOT 8669J - EXP 2028-05-14");
		s_Labels.Insert("TerjePillsHexacyanoferrate", "FERRIC HEXACYANOFERRATE 500 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH AFTER RADIOACTIVE CONTAMINATION.<br/>RADIATION L1 for 2 min<br/>OVERDOSE 0.3 (Moderate Risk). Binds fallout in the gut. Not a cure.<br/>LOT 7939J - EXP 2029-10-22");
		s_Labels.Insert("TerjePillsMexamine", "MEXAMINE 50 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH IMMEDIATELY BEFORE HEAVY RADIATION EXPOSURE.<br/>RADIATION L2 for 25 sec<br/>OVERDOSE 0.75 (High Risk). Very strong and very brief. Time it to the exposure.<br/>LOT 8091W - EXP 2030-06-17");
		s_Labels.Insert("TerjePillsIversan", "IVERSAN 12 MG - ORAL TABLET - CONTROLLED POISON<br/>UNLICENSED FORMULATION. NOT FIT FOR HUMAN USE.<br/>CAUSES FOOD POISONING<br/>OVERDOSE 0.5 (High Risk). Swallowing causes severe poisoning.<br/>LOT 1800L - EXP 2028-06-07");
		s_Labels.Insert("TerjePillsArsenic", "ARSENIC TRIOXIDE 200 MG - ORAL TABLET - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT SWALLOW.<br/>CAUSES FOOD POISONING<br/>OVERDOSE 2.5 (Lethal Risk). Poison. Causes fatal organ failure.<br/>LOT 7955N - EXP 2030-10-05");
		s_Labels.Insert("TerjePillsPotassiumCyanide", "POTASSIUM CYANIDE 300 MG - ORAL TABLET - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT SWALLOW.<br/>CAUSES FOOD POISONING<br/>OVERDOSE 1.5 (Severe Risk). Poison. Death follows within seconds.<br/>LOT 5827Z - EXP 2030-11-17");
		s_Labels.Insert("PainkillerTablets", "CODEINE 30 MG - ORAL CAPSULE - RX ONLY<br/>TAKE 1 CAPSULE BY MOUTH FOR PAIN.<br/>PAIN L1 for 5 min<br/>OVERDOSE 0.2 (Moderate Risk). May cause drowsiness. Habit forming.<br/>LOT 4254D - EXP 2029-08-14");
		s_Labels.Insert("TetracyclineAntibiotics", "TETRACYCLINE 250 MG - ORAL CAPSULE - RX ONLY<br/>TAKE 1 CAPSULE BY MOUTH FOR COLD/PNEUMONIA.<br/>COLD/PNEUMONIA L1 for 5 min<br/>OVERDOSE 0.45 (Moderate Risk). Avoid dairy. Finish the course.<br/>LOT 4537D - EXP 2029-05-09");
		s_Labels.Insert("CharcoalTablets", "CHARCOAL 500 MG - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH FOR FOOD POISONING.<br/>FOOD POISONING L1 for 5 min<br/>OVERDOSE 0.01 (Low Risk). Works only on recent poisoning.<br/>LOT 5433X - EXP 2030-08-05");
		s_Labels.Insert("ChelatingTablets", "CHELATION TABLETS (DMSA) 200 MG - ORAL TABLET - RX ONLY<br/>TAKE 1 TABLET BY MOUTH FOR SEVERE FOOD POISONING.<br/>FOOD POISONING L2 for 10 min<br/>OVERDOSE 0.6 (High Risk). Strong binder. Depletes minerals with repeat use.<br/>LOT 1810W - EXP 2029-04-20");
		s_Labels.Insert("VitaminBottle", "MULTIVITAMIN COMPLEX - ORAL TABLET<br/>TAKE 1 TABLET BY MOUTH DAILY TO SUPPORT IMMUNITY.<br/>IMMUNITY for 2 min<br/>OVERDOSE 0.01 (Low Risk). Dietary supplement. Not a medicine.<br/>LOT 2283H - EXP 2029-02-09");
		s_Labels.Insert("PurificationTablets", "WATER PURIFICATION TABLETS 8.5 MG - ORAL TABLET<br/>ADD 1 TABLET TO ONE LITRE OF WATER AND WAIT 30 MINUTES.<br/>TREATS WATER. NO EFFECT WHEN SWALLOWED.<br/>OVERDOSE 0.0 (None). For water treatment only. Do not swallow dry.<br/>LOT 3645J - EXP 2028-02-27");
		s_Labels.Insert("TerjeAmpouleAlcohol", "MEDICAL ALCOHOL 96% - INJECTION AMPOULE<br/>FOR CLEANING WOUNDS AND INSTRUMENTS. EXTERNAL USE ONLY.<br/>DISINFECTS WOUNDS AND SYRINGES. NOT FOR INJECTION.<br/>OVERDOSE 4.0 (Lethal Risk). Never inject. Injection is fatal.<br/>LOT 2286Z - EXP 2028-03-24");
		s_Labels.Insert("TerjeAmpouleAmoxivan", "AMOXIVAN (AMOXICILLIN) 1 G - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR COLD/PNEUMONIA.<br/>COLD/PNEUMONIA L2 for 15 min<br/>OVERDOSE 0.3 (Moderate Risk). Full-strength antibiotic. Space doses apart.<br/>LOT 5183W - EXP 2026-09-19");
		s_Labels.Insert("TerjeAmpouleKetarol", "KETAROL (KETOROLAC) 30 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR COLD/PNEUMONIA WITH PAIN.<br/>PAIN L1 for 20 min - COLD/PNEUMONIA L2 for 20 min<br/>OVERDOSE 0.5 (High Risk). Long acting. Do not stack with other painkillers.<br/>LOT 9647A - EXP 2026-04-15");
		s_Labels.Insert("TerjeAmpouleFlemoclav", "FLEMOCLAVE 1.2 G - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR COLD/PNEUMONIA AND SEPSIS.<br/>COLD/PNEUMONIA L3 for 20 min - SEPSIS for 20 min<br/>OVERDOSE 0.8 (High Risk). Maximum-strength antibiotic. Clinical use.<br/>LOT 4837B - EXP 2027-05-15");
		s_Labels.Insert("TerjeAmpouleImipenem", "IMIPENEM 500 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR COLD/PNEUMONIA AND SEPSIS.<br/>COLD/PNEUMONIA L3 for 15 min - SEPSIS for 15 min<br/>OVERDOSE 0.7 (High Risk). Last-line antibiotic. Reserve for sepsis.<br/>LOT 9632J - EXP 2027-07-17");
		s_Labels.Insert("TerjeAmpouleNovacaine", "NOVACAINE 2% - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR MODERATE PAIN.<br/>PAIN L2 for 20 min<br/>OVERDOSE 0.4 (Moderate Risk). May cause numbness and light-headedness.<br/>LOT 9150N - EXP 2028-06-26");
		s_Labels.Insert("TerjeAmpouleMorphine", "MORPHINOCIN 10 MG/ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR SEVERE PAIN.<br/>PAIN L3 for 14 min 10 sec<br/>OVERDOSE 0.52 (High Risk). Slows breathing. Habit forming.<br/>LOT 6578A - EXP 2026-06-15");
		s_Labels.Insert("TerjeAmpouleGexobarbital", "HEXOBARBITAL 500 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR SEVERE PAIN WITH SEDATION.<br/>PAIN L3 for 15 min<br/>OVERDOSE 0.65 (High Risk). Heavy sedation. Never combine with alcohol.<br/>LOT 3130X - EXP 2028-03-23");
		s_Labels.Insert("TerjeAmpouleKetamin", "KETAMINE 500 MG / 10 ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR SEVERE PAIN WHEN NOTHING ELSE WORKS.<br/>PAIN L3 for 10 min<br/>OVERDOSE 0.45 (Moderate Risk). Causes dissociation and confusion.<br/>LOT 9480L - EXP 2028-02-13");
		s_Labels.Insert("TerjeAmpouleMetoclopramid", "METOCLOPRAMID 10 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR SEVERE FOOD POISONING.<br/>FOOD POISONING L2 for 20 min<br/>OVERDOSE 0.4 (Moderate Risk). May cause restlessness and muscle stiffness.<br/>LOT 7337R - EXP 2026-10-02");
		s_Labels.Insert("TerjeAmpouleHeptral", "HEPTRAL (ADEMETIONINE) 400 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR SEVERE FOOD POISONING.<br/>FOOD POISONING L3 for 10 min<br/>OVERDOSE 0.6 (High Risk). Maximum strength. Space doses widely.<br/>LOT 3585L - EXP 2028-01-23");
		s_Labels.Insert("TerjeAmpouleNeirox", "NEIROX 250 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR CONCUSSION.<br/>CONCUSSION for 10 min<br/>OVERDOSE 0.6 (High Risk). Cerebral stimulant. Do not redose quickly.<br/>LOT 6352W - EXP 2026-03-02");
		s_Labels.Insert("TerjeAmpouleErythropoetin", "ERYTHROPOIETIN 4000 IU - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR BLOOD REGENERATION.<br/>BLOOD REGEN L1 for 10 min<br/>OVERDOSE 0.4 (Moderate Risk). Slow acting. Thickens the blood if overused.<br/>LOT 7102R - EXP 2026-12-21");
		s_Labels.Insert("TerjeAmpouleAdrenalin", "ADRENALINE (EPINEPHRINE) 1 MG/ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT TO FIGHT SHOCK AND RESTORE ALERTNESS.<br/>ADRENALINE for 3 min 40 sec<br/>OVERDOSE 0.3 (Moderate Risk). Raises heart rate sharply. Emergency use only.<br/>LOT 9721G - EXP 2028-03-17");
		s_Labels.Insert("TerjeAmpouleMetralindole", "METRALINDOLE 25 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR MENTAL HEALTH.<br/>MENTAL HEALTH L2 for 5 min<br/>OVERDOSE 0.1 (Low Risk). Mild sedation. The gentlest of the mood agents.<br/>LOT 5428L - EXP 2026-03-13");
		s_Labels.Insert("TerjeAmpouleActaparoxetine", "ACTAPAROXETINE 40 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR MENTAL HEALTH.<br/>MENTAL HEALTH L2 for 6 min 40 sec<br/>OVERDOSE 0.4 (Moderate Risk). May cause drowsiness for several minutes.<br/>LOT 9385C - EXP 2028-02-27");
		s_Labels.Insert("TerjeAmpouleAmitriptyline", "AMITRIPTYLINE 50 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR SEVERE MENTAL HEALTH LOSS.<br/>MENTAL HEALTH L3 for 10 min<br/>OVERDOSE 0.5 (High Risk). Heavy sedation. Do not drive after use.<br/>LOT 5649X - EXP 2027-12-15");
		s_Labels.Insert("TerjeAmpouleVaxicam", "VAXICAM INFLUENZA VACCINE 0.5 ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT BEFORE EXPOSURE TO PREVENT COLD/PNEUMONIA.<br/>COLD/PNEUMONIA IMMUNITY for 4 hr<br/>OVERDOSE 0.8 (High Risk). Preventive only. Does nothing once ill.<br/>LOT 4654V - EXP 2027-10-27");
		s_Labels.Insert("TerjeAmpouleZerivax", "ZERIVAX Z-VIRUS VACCINE 0.5 ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT BEFORE EXPOSURE TO PREVENT ZOMBIE VIRUS.<br/>ZOMBIE VIRUS IMMUNITY for 2 hr<br/>OVERDOSE 1.5 (Severe Risk). Preventive only. Severe reaction risk.<br/>LOT 9933W - EXP 2027-03-04");
		s_Labels.Insert("TerjeAmpouleRabivax", "RABIVAX RABIES VACCINE 1 ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT BEFORE EXPOSURE TO PREVENT RABIES.<br/>RABIES IMMUNITY for 4 hr<br/>OVERDOSE 1.3 (Severe Risk). Preventive only. Useless once symptoms begin.<br/>LOT 5990Z - EXP 2028-12-22");
		s_Labels.Insert("TerjeAmpouleRabinoline", "RABINOLINE ANTISERUM 5 ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT AFTER AN ANIMAL BITE TO TREAT RABIES.<br/>RABIES L2 for 10 min<br/>OVERDOSE 0.8 (High Risk). Give early. Serum reaction possible.<br/>LOT 1369V - EXP 2028-08-25");
		s_Labels.Insert("TerjeAmpouleRifampicyne", "RIFAMPICIN 600 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT FOR ADVANCED RABIES.<br/>RABIES L3 for 5 min<br/>OVERDOSE 1.35 (Severe Risk). Maximum strength. Give once, then wait it out.<br/>LOT 6485W - EXP 2026-08-11");
		s_Labels.Insert("TerjeAmpouleZivirol", "ZIVIROL EXPERIMENTAL ANTIDOTE 10 ML - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT IMMEDIATELY AFTER ZOMBIE VIRUS INFECTION.<br/>ZOMBIE VIRUS for 16 min 40 sec - HEALTH -25 - BLOOD -15 - SHOCK -100<br/>OVERDOSE 2.35 (Lethal Risk). Costs blood and health. One dose only.<br/>LOT 7977P - EXP 2028-02-22");
		s_Labels.Insert("TerjeAmpouleNeirocetal", "NEUROCETAL 200 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT AFTER CHEMICAL POISONING.<br/>CHEMICAL POISONING L2 for 8 min 20 sec<br/>OVERDOSE 1.25 (Severe Risk). Narrow safety margin. One dose only.<br/>LOT 8367J - EXP 2028-12-04");
		s_Labels.Insert("TerjeAmpoulePentacin", "PENTACIN (CA-DTPA) 250 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT AFTER HEAVY RADIOACTIVE CONTAMINATION.<br/>RADIATION L2 for 6 min 40 sec<br/>OVERDOSE 0.5 (High Risk). Strips minerals from the body. Limit doses.<br/>LOT 9981V - EXP 2027-09-13");
		s_Labels.Insert("TerjeAmpouleCarboxyme", "CARBOXYME 300 MG - INJECTION AMPOULE - RX ONLY<br/>DRAW WITH A STERILE SYRINGE AND INJECT AFTER PROLONGED RADIATION EXPOSURE.<br/>RADIATION L2 for 10 min<br/>OVERDOSE 0.6 (High Risk). Long acting. Limit repeat doses.<br/>LOT 6097X - EXP 2026-12-22");
		s_Labels.Insert("TerjeAmpouleBeladonna", "BELLADONNA EXTRACT 1 ML - INJECTION AMPOULE - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT INJECT.<br/>CAUSES PAIN - CAUSES CONCUSSION<br/>OVERDOSE 3.8 (Lethal Risk). Poison. Causes delirium and collapse.<br/>LOT 8965J - EXP 2027-01-27");
		s_Labels.Insert("TerjeAmpouleStrychnine", "STRYCHNINE 5 MG/ML - INJECTION AMPOULE - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT INJECT.<br/>CAUSES CONCUSSION - BLOOD -1000 - WATER -5000<br/>OVERDOSE 3.2 (Lethal Risk). Poison. Causes violent convulsions.<br/>LOT 2913H - EXP 2027-12-24");
		s_Labels.Insert("TerjeAmpouleKonyin", "KONYIN (CONIINE) 2 ML - INJECTION AMPOULE - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT INJECT.<br/>SEDATION +100 for 5 min<br/>OVERDOSE 3.0 (Lethal Risk). Poison. Causes paralysis and unconsciousness.<br/>LOT 4693V - EXP 2028-11-09");
		s_Labels.Insert("TerjeAmpouleArsenic", "ARSENIC TRIOXIDE 10 MG/ML - INJECTION AMPOULE - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT INJECT.<br/>HEALTH -50<br/>OVERDOSE 5.0 (Lethal Risk). Poison. Fatal multi-organ failure.<br/>LOT 7094D - EXP 2028-08-07");
		s_Labels.Insert("TerjeAmpoulePotassiumCyanide", "POTASSIUM CYANIDE 300 MG/ML - INJECTION AMPOULE - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT INJECT.<br/>WATER -5000 - ENERGY -5000<br/>OVERDOSE 5.0 (Lethal Risk). Poison. Death follows within seconds.<br/>LOT 1198Y - EXP 2027-07-03");
		s_Labels.Insert("TerjeInjectorPromidol", "PROMIDOL 40 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR SEVERE PAIN.<br/>PAIN L3 for 10 min<br/>OVERDOSE 0.45 (Moderate Risk). Strong opioid. Habit forming.<br/>LOT 9534S - EXP 2029-03-22");
		s_Labels.Insert("TerjeInjectorPropital", "PROPITAL 100 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR PAIN AND RAPID WOUND RECOVERY.<br/>PAIN L2 for 3 min - HEALTH REGEN for 45 sec<br/>OVERDOSE 0.75 (High Risk). Combat stimulant. Habit forming.<br/>LOT 5203C - EXP 2028-04-05");
		s_Labels.Insert("TerjeInjectorReanimatal", "REANIMATAL 200 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH TO REVIVE A COLLAPSING CASUALTY.<br/>PAIN L3 for 4 min - HEALTH REGEN for 3 min - SHOCK -75<br/>OVERDOSE 1.5 (Severe Risk). Buys minutes only, and takes a heavy toll to do it.<br/>LOT 8365K - EXP 2029-05-12");
		s_Labels.Insert("TerjeInjectorAmoxiclav", "AMOXICLAV 1.2 G - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR COLD/PNEUMONIA AND SEPSIS.<br/>COLD/PNEUMONIA L3 for 30 min - SEPSIS for 5 min<br/>OVERDOSE 0.6 (High Risk). Longest-acting antibiotic carried. Do not stack.<br/>LOT 7193X - EXP 2027-08-23");
		s_Labels.Insert("TerjeInjectorTopoizomeraza", "TOPOISOMERASE 400 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR COLD/PNEUMONIA AND SEPSIS.<br/>COLD/PNEUMONIA L3 for 15 min - SEPSIS for 10 min<br/>OVERDOSE 0.65 (High Risk). Broad spectrum. Reserve for sepsis.<br/>LOT 8495N - EXP 2027-08-07");
		s_Labels.Insert("TerjeInjectorNeirox", "NEIROX 250 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR CONCUSSION.<br/>CONCUSSION for 8 min 20 sec<br/>OVERDOSE 0.3 (Moderate Risk). Cerebral stimulant. May cause jitters.<br/>LOT 1012J - EXP 2027-01-08");
		s_Labels.Insert("TerjeInjectorErytromixelin", "ERYTROMIXELIN 5 ML - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH TO SLOW THE BLEEDING RATE AND REBUILD BLOOD.<br/>BLEEDING RATE L3 for 5 min - BLOOD REGEN L2 for 2 min 30 sec<br/>OVERDOSE 0.32 (Moderate Risk). Does not replace a bandage or tourniquet.<br/>LOT 6761S - EXP 2028-07-22");
		s_Labels.Insert("TerjeInjectorErythropoietin", "ERYTHROPOIETIN 4000 IU - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR BLOOD REGENERATION.<br/>BLOOD REGEN L1 for 15 min<br/>OVERDOSE 0.4 (Moderate Risk). Slow acting. Thickens the blood if overused.<br/>LOT 7164G - EXP 2029-07-18");
		s_Labels.Insert("TerjeInjectorStomaproxidal", "STOMAPROXIDAL 250 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR SEVERE FOOD POISONING.<br/>FOOD POISONING L3 for 15 min<br/>OVERDOSE 0.68 (High Risk). Maximum strength. One dose per incident.<br/>LOT 5737S - EXP 2027-09-18");
		s_Labels.Insert("TerjeInjectorRabinucoline", "RABINUCOLINE ANTISERUM 5 ML - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH AFTER AN ANIMAL BITE TO TREAT RABIES.<br/>RABIES L3 for 15 min<br/>OVERDOSE 1.46 (Severe Risk). Maximum strength. Give once and monitor.<br/>LOT 5032F - EXP 2027-07-26");
		s_Labels.Insert("TerjeInjectorAmfitalicyne", "AMFITALICYNE 60 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR SEVERE MENTAL HEALTH LOSS.<br/>MENTAL HEALTH L3 for 8 min 40 sec<br/>OVERDOSE 0.6 (High Risk). Psychotropic. Heavy sedation possible.<br/>LOT 8396V - EXP 2028-09-28");
		s_Labels.Insert("TerjeInjectorZivirol", "ZIVIROL EXPERIMENTAL ANTIDOTE 10 ML - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH IMMEDIATELY AFTER ZOMBIE VIRUS INFECTION.<br/>ZOMBIE VIRUS for 20 min - HEALTH -20 - BLOOD -10 - SHOCK -100<br/>OVERDOSE 2.5 (Lethal Risk). Costs blood and health. One dose only.<br/>LOT 9612D - EXP 2029-12-07");
		s_Labels.Insert("TerjeInjectorNovichek", "NOVICHEK NERVE AGENT - SINGLE-USE AUTO-INJECTOR - CONTROLLED POISON<br/>NOT A MEDICINE. DO NOT USE.<br/>SHOCK -100<br/>OVERDOSE 5.0 (Lethal Risk). Military nerve agent. Exposure is fatal.<br/>LOT 3419V - EXP 2029-11-01");
		s_Labels.Insert("Morphine", "MORPHINE 10 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH FOR SEVERE PAIN.<br/>PAIN L3 for 5 min<br/>OVERDOSE 0.75 (High Risk). Slows breathing. Habit forming.<br/>LOT 1721G - EXP 2027-01-27");
		s_Labels.Insert("Epinephrine", "EPINEPHRINE 0.3 MG - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH TO REVERSE SHOCK AND RESTORE ALERTNESS.<br/>ADRENALINE for 12 min<br/>OVERDOSE 0.55 (High Risk). Raises heart rate sharply. One dose per episode.<br/>LOT 2174W - EXP 2028-02-21");
		s_Labels.Insert("AntiChemInjector", "NBC ANTIDOTE (ATROPINE / PRALIDOXIME) - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH IMMEDIATELY AFTER CHEMICAL POISONING.<br/>CHEMICAL POISONING L3 for 3 min<br/>OVERDOSE 1.1 (Severe Risk). Military issue. One dose per exposure, never two.<br/>LOT 1356Y - EXP 2029-03-07");
		s_Labels.Insert("TerjeAntiradInjector", "ANTI-RADIATION AGENT - SINGLE-USE AUTO-INJECTOR - RX ONLY<br/>PRESS FIRMLY AGAINST THE OUTER THIGH AFTER RADIATION EXPOSURE.<br/>RADIATION. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). One dose per exposure. Not a cure for burns.<br/>LOT 5297V - EXP 2028-11-27");
		s_Labels.Insert("TerjeSalveViprosal", "VIPROSAL (CAMPHOR / TURPENTINE) 30 G - TOPICAL OINTMENT, TUBE<br/>APPLY A THIN LAYER TO BRUISING AND RUB IN GENTLY.<br/>HEMATOMA L1 for 10 min<br/>OVERDOSE 0.0 (None). External use only. Longest acting of the three.<br/>LOT 5665A - EXP 2030-09-11");
		s_Labels.Insert("TerjeSalveCapsicum", "CAPSICUM OINTMENT 30 G - TOPICAL OINTMENT, TUBE<br/>APPLY A THIN LAYER TO BRUISING.<br/>HEMATOMA L1 for 6 min 40 sec<br/>OVERDOSE 0.0 (None). External use only. Burns on broken skin.<br/>LOT 2590K - EXP 2027-01-23");
		s_Labels.Insert("TerjeSalveFinalgon", "FINALGON (NONIVAMIDE) 20 G - TOPICAL OINTMENT, TUBE<br/>APPLY A SMALL AMOUNT TO BRUISING.<br/>HEMATOMA L1 for 5 min<br/>OVERDOSE 0.0 (None). External use only. Fast, short acting, strong burn.<br/>LOT 1179P - EXP 2027-02-23");
		s_Labels.Insert("TerjeDrinkYaguar", "YAGUAR(R) ENERGY DRINK - 500 ML CAN<br/>DRINK TO FIGHT EXHAUSTION. STRONGEST FORMULA STOCKED.<br/>WAKEFULNESS +10 for 1 sec<br/>OVERDOSE 0.0 (None). Very high caffeine. Not a substitute for sleep.<br/>LOT 2842H - BEST BY 2030-03-23");
		s_Labels.Insert("TerjeDrinkMadBull", "MADBULL(R) ENERGY DRINK - 500 ML CAN<br/>DRINK TO FIGHT EXHAUSTION AND STAY AWAKE.<br/>WAKEFULNESS +8 for 1 sec<br/>OVERDOSE 0.0 (None). High caffeine. Not a substitute for sleep.<br/>LOT 5434P - BEST BY 2031-03-05");
		s_Labels.Insert("TerjeDrink6Energy", "6-HOUR ENERGY(R) - 500 ML CAN<br/>DRINK TO FIGHT EXHAUSTION AND STAY AWAKE.<br/>WAKEFULNESS +8 for 1 sec<br/>OVERDOSE 0.0 (None). High caffeine. Not a substitute for sleep.<br/>LOT 3856V - BEST BY 2030-05-18");
		s_Labels.Insert("TerjeDrinkGang", "GANG(R) ENERGY DRINK - 500 ML CAN<br/>DRINK TO FIGHT EXHAUSTION.<br/>WAKEFULNESS +6 for 1 sec<br/>OVERDOSE 0.0 (None). Moderate caffeine. Not a substitute for sleep.<br/>LOT 5376E - BEST BY 2029-10-20");
		s_Labels.Insert("TerjeDrinkPrayboy", "PRAYBOY(R) ENERGY DRINK - 500 ML CAN<br/>DRINK TO TAKE THE EDGE OFF TIREDNESS.<br/>WAKEFULNESS +4 for 1 sec<br/>OVERDOSE 0.0 (None). Mild formula. Not a substitute for sleep.<br/>LOT 8324Y - BEST BY 2030-06-09");
		s_Labels.Insert("TerjeSurgicalTool_White", "MEDICAL BOWL WITH INSTRUMENT - TRAY, REUSABLE<br/>USE TO REMOVE FRAGMENTS AND CLOSE DEEP WOUNDS.<br/>WOUND SURGERY. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Sterilise before every use.<br/>LOT 9752C - STERILE UNTIL 2030-01-16");
		s_Labels.Insert("TerjeSurgicalTool_Ceramic", "MEDICAL BOWL WITH INSTRUMENT - TRAY, REUSABLE<br/>USE TO REMOVE FRAGMENTS AND CLOSE DEEP WOUNDS.<br/>WOUND SURGERY. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Sterilise before every use.<br/>LOT 9752C - STERILE UNTIL 2030-01-16");
		s_Labels.Insert("TerjeSurgicalKit", "FIELD SURGICAL KIT - SEALED POUCH, MULTI-USE<br/>USE TO REMOVE FRAGMENTS AND CLOSE DEEP WOUNDS.<br/>WOUND SURGERY. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Contents are single-use. Discard when spent.<br/>LOT 4680A - STERILE UNTIL 2031-12-26");
		s_Labels.Insert("TerjeFirstAidKitIndividual_Black", "INDIVIDUAL FIRST AID KIT (IFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT YOUR OWN WOUNDS IN THE FIELD.<br/>WOUND TREATMENT. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 8321X - STERILE UNTIL 2031-07-22");
		s_Labels.Insert("TerjeFirstAidKitIndividual_Brown", "INDIVIDUAL FIRST AID KIT (IFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT YOUR OWN WOUNDS IN THE FIELD.<br/>WOUND TREATMENT. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 8321X - STERILE UNTIL 2031-07-22");
		s_Labels.Insert("TerjeFirstAidKitIndividual_Green", "INDIVIDUAL FIRST AID KIT (IFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT YOUR OWN WOUNDS IN THE FIELD.<br/>WOUND TREATMENT. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 8321X - STERILE UNTIL 2031-07-22");
		s_Labels.Insert("TerjeFirstAidKitIndividual_Camo", "INDIVIDUAL FIRST AID KIT (IFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT YOUR OWN WOUNDS IN THE FIELD.<br/>WOUND TREATMENT. VALUES SET BY SERVER CONFIG.<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 8321X - STERILE UNTIL 2031-07-22");
		s_Labels.Insert("TerjeFirstAidKitAdvance_Black", "ADVANCED FIRST AID KIT (AFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT SERIOUS WOUNDS IN THE FIELD.<br/>BLEEDING RATE L3 for 1 min<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 9842J - STERILE UNTIL 2031-03-06");
		s_Labels.Insert("TerjeFirstAidKitAdvance_Brown", "ADVANCED FIRST AID KIT (AFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT SERIOUS WOUNDS IN THE FIELD.<br/>BLEEDING RATE L3 for 1 min<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 9842J - STERILE UNTIL 2031-03-06");
		s_Labels.Insert("TerjeFirstAidKitAdvance_Green", "ADVANCED FIRST AID KIT (AFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT SERIOUS WOUNDS IN THE FIELD.<br/>BLEEDING RATE L3 for 1 min<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 9842J - STERILE UNTIL 2031-03-06");
		s_Labels.Insert("TerjeFirstAidKitAdvance_Camo", "ADVANCED FIRST AID KIT (AFAK) - SEALED POUCH, MULTI-USE<br/>USE TO TREAT SERIOUS WOUNDS IN THE FIELD.<br/>BLEEDING RATE L3 for 1 min<br/>OVERDOSE 0.0 (None). Refill after use. Contents are consumed.<br/>LOT 9842J - STERILE UNTIL 2031-03-06");
	}
}

modded class ItemBase
{
	override bool DescriptionOverride(out string output)
	{
		string label = LLGMedicineLabels.Get(GetType());
		if (label != "")
		{
			output = label;
			return true;
		}
		return super.DescriptionOverride(output);
	}
}
